### ISSUE TITLE
How can we please have a doc showing how to make a message here from a string?

### ISSUE THREAD

**Issue by smekers** [matrix-org/matrix-rust-components-swift#17]
Not really an issue I'm just so lost and I don't see any examples how to do that with the current version

https://github.com/matrix-org/matrix-rust-components-swift/blob/3f294cd61bb73a9b29cede2b1fd22c5c8273686c/Sources/MatrixRustSDK/matrix_sdk_ffi.swift#L8435

**Comment by stefanceriu** [comment]
This is not the right place for docs as `matrix-rust-components-swift` just packages FFI bindings for the rust-sdk i.e. https://github.com/matrix-org/matrix-rust-sdk/blob/main/bindings/matrix-sdk-ffi/src/timeline/mod.rs#L236

Otherwise your best bet is to just look at what ElementX does with it https://github.com/element-hq/element-x-ios/blob/develop/ElementX/Sources/Services/Timeline/TimelineProxy.swift#L371
